vim.keymap.set('', 'j', 'gj', { noremap = true, silent = false })
vim.api.nvim_set_keymap('', 'j', 'gj', { noremap = true, silent = false })
vim.api.nvim_set_keymap('', 'gj', 'j', { noremap = true, silent = false })
vim.api.nvim_set_keymap('', 'k', 'gk', { noremap = true, silent = false })
vim.api.nvim_set_keymap('', 'gk', 'k', { noremap = true, silent = false })
vim.api.nvim_set_keymap('', 'zl', 'zL', { noremap = true, silent = false })
vim.api.nvim_set_keymap('', 'zh', 'zH', { noremap = true, silent = false })
vim.api.nvim_set_keymap('n', 'Y', 'y$', { noremap = true, silent = false })
vim.api.nvim_set_keymap('n', '<leader>/', ':nohlsearch<CR>', { silent = false })
